### ISSUE TITLE
Can't set prefix to /usr/

### ISSUE THREAD

**Issue by mhostetter** [gnuradio/pybombs#303]
Not sure if this is an issue, but here we go.

I found that I can't just set the installation prefix to `/usr/`.  I get this error message:
```
pi@raspberrypi:~ $ pybombs prefix init /usr/ -a myprefix
PyBombs.prefix - ERROR - Cannot write to prefix path `/usr'.
```

I am able to set the prefix to `/usr/` as root, though.
```
pi@raspberrypi:~ $ sudo pybombs prefix init /usr/ -a myprefix
PyBombs.prefix - INFO - Initializing PyBOMBS prefix in `/usr'...
PyBombs.ConfigManager - INFO - Creating new config file /root/.pybombs/config.yml
```

But then I need to add the recipes as root as well.  Is this intended usage?

My use case is I'm trying to install GNU Radio on a Raspberry Pi.  I started with the GNU Radio binaries using `apt-get`.  I found I needed `gr-osmosdr` and wanted to install it with PyBOMBS into `/usr/` where GNU Radio was installed by default.

Thanks!

**Comment by mbr0wn** [comment]
Well, this is kind of intentional. Clearly you need elevated privileges to write to `/usr`, so the sudo is required anyhow.

I say 'kind of' because ideally, PyBOMBS would realize this and then ask for elevated privileges. However, this only gets interesting if you're planning to put source, config and binaries into separate directories. Until now, manually appending sudo is the right way to do this.
