### ISSUE TITLE
Gnu-radio installation on Ubuntu with Pybombs fails

### ISSUE THREAD

**Issue by asim800** [gnuradio/pybombs#428]
Hi,

I was able to install gnuradio with build-gnuradio script after making following changes to fix CMake error of undefined reference to boost::program_options. 
export CC=/usr/bin/gcc-6
export CXX=/usr/bin/g++-6

However, I'd like to install gnuradio using pybombs so that I can add recipes later and use OOT flow. 

I ran the following command
susudo pybombs prefix init /usr/local -a usrlocal
sudo pybombs config default_prefix /usr/local/gr
sudo pybombs -v recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git
sudo pybombs -v recipes add gr-etcetera git+https://github.com/gnuradio/gr-etcetera.git
sudo pybombs install uhd

Here again I am getting another undefined reference to boost library. I couldn't find the GCC compiler version supported by pybombs. Is there some documentation regarding the version numbers supporting tool chain?

../lib/libuhd.so.3.11: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
../lib/libuhd.so.3.11: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status

Thankyou

Machine info:
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
uname -a
Linux WH 4.4.0-67-generic #88-Ubuntu SMP Wed Mar 8 16:34:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Here's slightly longer error log:
```
PyBOMBS.install_manager - DEBUG - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.Fetcher.git - DEBUG - Requirements met.
PyBOMBS.Fetcher.git - DEBUG - Using url - https://github.com/EttusResearch/uhd.git
PyBOMBS._process_thread() - DEBUG - Executing command `git clone https://github.com/EttusResearch/uhd.git uhd -b master'
Cloning:     (100%) [===============================================================================================]
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 0
PyBOMBS.Inventory - DEBUG - Setting state to `fetched'
PyBOMBS.Inventory - DEBUG - Saving inventory to file /home/hercules/coding/gnur/uhd/host/lib/.pybombs/inventory.yml...
PyBOMBS.Requirer - DEBUG - Requiring packages on host system: []
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pip
PyBOMBS.PackageManager - DEBUG - pip is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager apt
PyBOMBS.PackageManager - DEBUG - apt is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager yumdnf
PyBOMBS.PackageManager - DEBUG - yumdnf is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager port
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager brew
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pacman
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager portage
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pymod
PyBOMBS.PackageManager - DEBUG - pymod is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pkgconfig
PyBOMBS.PackageManager - DEBUG - pkgconfig is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager cmd
PyBOMBS.PackageManager - DEBUG - cmd is supported!
PyBOMBS.PackageManager - DEBUG - Using binary packagers: ['pip', 'apt', 'yumdnf', 'pymod', 'pkgconfig', 'cmd']
PyBOMBS.install_manager - DEBUG - Phase 1: Creating install tree and installing binary packages:
PyBOMBS.PackageManager - DEBUG - Checking if package build-essential is installable...
PyBOMBS.Packager.apt - DEBUG - Package build-essential has version 12.1 in repositories
PyBOMBS.PackageManager - DEBUG - Checking if package build-essential is installed...
PyBOMBS.Packager.apt - DEBUG - Package build-essential has version 12.1 installed
PyBOMBS.install_manager - DEBUG - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.Requirer - DEBUG - Requirements met.
PyBOMBS.Packager.source - DEBUG - Using build directory: /home/hercules/coding/gnur/uhd/host/lib/src/uhd/host/build
PyBOMBS.Packager.source - DEBUG - Configuring recipe uhd
PyBOMBS.Packager.source - DEBUG - Using vars - {'config_opt': '', 'builddir': '/home/hercules/coding/gnur/uhd/host/lib/src/uhd/host/build'}
PyBOMBS.Packager.source - DEBUG - In cwd - /home/hercules/coding/gnur/uhd/host/lib/src/uhd/host/build
PyBOMBS._process_thread() - DEBUG - Executing command `$ cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/hercules/coding/gnur/uhd/host/lib  -Wno-dev'
Configuring: (100%) [===============================================================================================]
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 0
PyBOMBS.Packager.source - DEBUG - Configure successful.
PyBOMBS.Inventory - DEBUG - Setting state to `configured'
PyBOMBS.Inventory - DEBUG - Saving inventory to file /home/hercules/coding/gnur/uhd/host/lib/.pybombs/inventory.yml...
PyBOMBS.Packager.source - DEBUG - Building recipe uhd
PyBOMBS.Packager.source - DEBUG - In cwd - /home/hercules/coding/gnur/uhd/host/lib/src/uhd/host/build
PyBOMBS._process_thread() - DEBUG - Executing command `$ make -j4'
Building:    (100%) [===============================================================================================]
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 2
PyBOMBS.Packager.source - DEBUG - Building recipe uhd
PyBOMBS.Packager.source - DEBUG - In cwd - /home/hercules/coding/gnur/uhd/host/lib/src/uhd/host/build
PyBOMBS._process_thread() - DEBUG - Executing command `$ make -j1'
[ 61%] Built target uhd
[ 62%] Linking CXX executable sync_to_gps
../lib/libuhd.so.3.11: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
../lib/libuhd.so.3.11: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/sync_to_gps.dir/build.make:107: recipe for target 'examples/sync_to_gps' failed
make[2]: *** [examples/sync_to_gps] Error 1
CMakeFiles/Makefile2:414: recipe for target 'examples/CMakeFiles/sync_to_gps.dir/all' failed
make[1]: *** [examples/CMakeFiles/sync_to_gps.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 2
PyBOMBS.Packager.source - ERROR - Build failed. See output above for error messages.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package uhd:
Build failed.
PyBOMBS.install_manager - ERROR - Error installing package uhd. Aborting.
```

**Comment by mbr0wn** [comment]
Which Ubuntu version were you using?

There's an ABI issue we know about, but this doesn't look like it's a PyBOMBS issue.

**Comment by asim800** [comment]
Thanks for looking into it.

It turns out that I get this error when I used version 6 of gcc/g++ with pybombs and I needed to use gcc/g++ version 5 to get around this problem. 

One lingering question that I have was that I was able to get gnuradio/uhd installed with gcc/g++ version 6 using build-gnuradio script from (www.sbrac.org/files/build-gnuradio).

regards

**Comment by febs** [comment]
I think this should not be closed, since it requires a very specific user intervention at the Operating System level to work. Thanks.

**Comment by curtcorum** [comment]
I concur with Fabio @febs 
I am having similar issues with pybombs installing gnuradio on Ubuntu 16.04, after trying a number of variations from #428 and #448 as well as other links.

My goal is to build and use gnuradio with uhd and controlport support and pybombs seems to be the way to do it. No easy combination of existing  ubuntu/deb packages seems to support it (due to thrift dependency?)

curt@curt--laptop:~$ gcc --version
gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010

curt@curt--laptop:~$ pybombs --version
2.3.2

As of now after purging all packages related to gnuradio and uhd and concentraing on gcc-5 I can get thrift and uhd to build. Gnuradio still will not build due to the error:

[ 14%] Building CXX object gr-blocks/lib/CMakeFiles/gnuradio-blocks.dir/float_array_to_int.cc.o
In file included from /usr/include/c++/5/cstdint:35:0,
                 from /home/curt/pybombs_180605/src/gnuradio/gr-blocks/lib/float_array_to_int.cc:30:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

Any ideas?

thanks,
Curt

Full output:

curt@curt--laptop:~$ nice pybombs -v rebuild gnuradio
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: /etc/pybombs/config.yml
PyBOMBS.ConfigManager - DEBUG - Parsing config file failed (/etc/pybombs/config.yml).
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: /home/curt/.pybombs/config.yml
PyBOMBS.ConfigManager - DEBUG - New config items: ordereddict([('git-cache', '/home/curt/.pybombs/gitcache'), ('elevate_pre_args', ['sudo', '-H']), ('makewidth', 4), ('packagers', 'pip,apt,pymod,pkgconfig,cmd'), ('default_prefix', 'myprefix')])
PyBOMBS.ConfigManager - DEBUG - Template directory: /usr/local/lib/python2.7/dist-packages/pybombs/templates
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Inspecting config file: /home/curt/.pybombs/config.yml
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Resolving prefix alias `myprefix'.
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Using default_prefix as prefix (/home/curt/pybombs_180605)
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Choosing default prefix config dir: /home/curt/pybombs_180605/.pybombs
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Inspecting config file: /home/curt/pybombs_180605/.pybombs/config.yml
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Prefix source dir is: /home/curt/pybombs_180605/src
PyBOMBS.Inventory - DEBUG - Trying to load inventory file /home/curt/pybombs_180605/.pybombs/inventory.yml...
PyBOMBS.ConfigManager.PrefixInfo - DEBUG - Prefix-local recipe dir is: /home/curt/pybombs_180605/.pybombs/recipes
PyBOMBS.ConfigManager - DEBUG - Reading config info from file: /home/curt/pybombs_180605/.pybombs/config.yml
PyBOMBS.ConfigManager - DEBUG - New config items: {}
PyBOMBS.ConfigManager - DEBUG - Full list of recipe locations: ['/home/curt/pybombs_180605/.pybombs/recipes', '/home/curt/.pybombs/recipes/gr-recipes', '/home/curt/.pybombs/recipes/gr-etcetera', '/usr/local/lib/python2.7/dist-packages/pybombs/recipes']
PyBOMBS.ConfigManager - DEBUG - Named recipe locations: {'gr-etcetera': 'git+https://github.com/gnuradio/gr-etcetera.git', 'gr-recipes': 'git+https://github.com/gnuradio/gr-recipes.git'}
PyBOMBS - INFO - PyBOMBS Version 2.3.2
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/curt/pybombs_180605/.pybombs/recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/curt/pybombs_180605/.pybombs/recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 0 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/curt/.pybombs/recipes/gr-recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/curt/.pybombs/recipes/gr-recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 189 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /home/curt/.pybombs/recipes/gr-etcetera
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/home/curt/.pybombs/recipes/gr-etcetera' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 97 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.RecipeListManager - DEBUG - Adding recipe location: /usr/local/lib/python2.7/dist-packages/pybombs/recipes
PyBOMBS.RecipeListManager - DEBUG - Scanning directory '/usr/local/lib/python2.7/dist-packages/pybombs/recipes' for recipes...
PyBOMBS.RecipeListManager - DEBUG - Found 11 new recipes.
PyBOMBS.RecipeListManager - DEBUG - Loading templates.
PyBOMBS.rebuild - DEBUG - Initializing command class for command rebuild
PyBOMBS.rebuild - DEBUG - Install tree:
|
\- gnuradio
PyBOMBS.rebuild - INFO - Rebuilding package: gnuradio
PyBOMBS.Inventory - DEBUG - Setting state to `fetched'
PyBOMBS.Requirer - DEBUG - Requiring packages on host system: []
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pip
PyBOMBS.PackageManager - DEBUG - pip is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager apt
PyBOMBS.PackageManager - DEBUG - apt is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pymod
PyBOMBS.PackageManager - DEBUG - pymod is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager pkgconfig
PyBOMBS.PackageManager - DEBUG - pkgconfig is supported!
PyBOMBS.PackageManager - DEBUG - Attempting to add binary package manager cmd
PyBOMBS.PackageManager - DEBUG - cmd is supported!
PyBOMBS.PackageManager - DEBUG - Using binary packagers: ['pip', 'apt', 'pymod', 'pkgconfig', 'cmd']
PyBOMBS.install_manager - DEBUG - Phase 1: Creating install tree and installing binary packages:
PyBOMBS.PackageManager - DEBUG - Checking if package build-essential is installable...
PyBOMBS.Packager.apt - DEBUG - Package build-essential has version 12.1 in repositories
PyBOMBS.PackageManager - DEBUG - Checking if package build-essential is installed...
PyBOMBS.Packager.apt - DEBUG - Package build-essential has version 12.1 installed
PyBOMBS.install_manager - DEBUG - Phase 2: Recursively installing source packages to prefix:
PyBOMBS.Requirer - DEBUG - Requirements met.
PyBOMBS.Packager.source - DEBUG - Using build directory: /home/curt/pybombs_180605/src/gnuradio/build
PyBOMBS.Packager.source - INFO - Removing old build directory.
PyBOMBS.Packager.source - DEBUG - Configuring recipe gnuradio
PyBOMBS.Packager.source - DEBUG - Using vars - ordereddict([('config_opt', ' -DENABLE_DOXYGEN=$builddocs -DENABLE_GR_AUDIO=ON -DENABLE_GR_BLOCKS=ON -DENABLE_GR_DIGITAL=ON -DENABLE_GR_FEC=ON -DENABLE_GR_FFT=ON -DENABLE_GR_FILTER=ON -DENABLE_GR_QTGUI=ON -DENABLE_GR_UHD=ON -DENABLE_PYTHON=ON -DENABLE_VOLK=ON -DENABLE_GRC=ON '), ('builddir', '/home/curt/pybombs_180605/src/gnuradio/build')])
PyBOMBS.Packager.source - DEBUG - In cwd - /home/curt/pybombs_180605/src/gnuradio/build
PyBOMBS._process_thread() - DEBUG - Executing command `$ cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/curt/pybombs_180605  -DENABLE_DOXYGEN=OFF -DENABLE_GR_AUDIO=ON -DENABLE_GR_BLOCKS=ON -DENABLE_GR_DIGITAL=ON -DENABLE_GR_FEC=ON -DENABLE_GR_FFT=ON -DENABLE_GR_FILTER=ON -DENABLE_GR_QTGUI=ON -DENABLE_GR_UHD=ON -DENABLE_PYTHON=ON -DENABLE_VOLK=ON -DENABLE_GRC=ON  -Wno-dev'
Configuring: (100%) [==========================================================================================================================]
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 0
PyBOMBS.Packager.source - DEBUG - Configure successful.
PyBOMBS.Inventory - DEBUG - Setting state to `configured'
PyBOMBS.Inventory - DEBUG - Saving inventory to file /home/curt/pybombs_180605/.pybombs/inventory.yml...
PyBOMBS.Packager.source - DEBUG - Building recipe gnuradio
PyBOMBS.Packager.source - DEBUG - In cwd - /home/curt/pybombs_180605/src/gnuradio/build
PyBOMBS._process_thread() - DEBUG - Executing command `$ make -j4'
Building:    (100%) [==========================================================================================================================]
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 2
PyBOMBS.Packager.source - DEBUG - Building recipe gnuradio
PyBOMBS.Packager.source - DEBUG - In cwd - /home/curt/pybombs_180605/src/gnuradio/build
PyBOMBS._process_thread() - DEBUG - Executing command `$ make -j1'
[  4%] Built target volk_obj
[  4%] Built target volk
[  4%] Built target volk_test_all
[  5%] Built target volk-config-info
[  5%] Built target volk_profile
[  5%] Built target pygen_volk_python_volk_modtool_97e88
[  5%] Built target pygen_volk_python_volk_modtool_670ee
[  6%] Built target pmt_generated
[  6%] Built target gnuradio-pmt
[  9%] Built target gnuradio-runtime
[ 10%] Built target test-gnuradio-runtime
[ 10%] Built target gr_runtime_test
[ 10%] Built target test-gnuradio-pmt
[ 10%] Built target gr_pmt_test
[ 10%] Built target gnuradio-config-info
[ 10%] Built target pmt_swig_swig_doc
[ 10%] Built target _pmt_swig_swig_tag
[ 10%] Built target pmt_swig_gnuradio_runtime_swig_7dd5e
[ 11%] Built target pygen_gnuradio_runtime_swig_e0b57
[ 11%] Built target _pmt_swig
[ 11%] Built target pmt_swig
[ 11%] Built target runtime_swig_swig_doc
[ 11%] Built target _runtime_swig_swig_tag
[ 11%] Built target runtime_swig_gnuradio_runtime_swig_7dd5e
[ 11%] Built target _runtime_swig
[ 11%] Built target pygen_gnuradio_runtime_swig_1c8f9
[ 12%] Built target pygen_gnuradio_runtime_python_gnuradio_a4271
[ 12%] Built target pygen_gnuradio_runtime_python_gnuradio_gr_e6591
[ 12%] Built target pygen_gnuradio_runtime_python_gnuradio_gru_25f05
[ 12%] Built target pygen_gnuradio_runtime_python_gnuradio_ctrlport_cf5a0
[ 12%] Built target pygen_gnuradio_runtime_python_gnuradio_ctrlport_f9135
[ 12%] Built target pygen_gnuradio_runtime_python_gnuradio_ctrlport_66fa9
[ 12%] Built target pygen_gnuradio_runtime_python_gnuradio_ctrlport_17ad1
[ 12%] Built target pygen_gnuradio_runtime_python_pmt_b55b0
[ 12%] Built target pygen_gnuradio_runtime_examples_mp_sched_085ed
[ 12%] Built target pygen_gnuradio_runtime_examples_network_08636
[ 12%] Built target pygen_gnuradio_runtime_examples_volk_benchmark_9349c
[ 14%] Built target blocks_generated_includes
[ 14%] Building CXX object gr-blocks/lib/CMakeFiles/gnuradio-blocks.dir/float_array_to_int.cc.o
In file included from /usr/include/c++/5/cstdint:35:0,
                 from /home/curt/pybombs_180605/src/gnuradio/gr-blocks/lib/float_array_to_int.cc:30:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
/home/curt/pybombs_180605/src/gnuradio/gr-blocks/lib/float_array_to_int.cc:32:14: error: ‘int64_t’ does not name a type
 static const int64_t MAX_INT =  INT32_MAX;
              ^
/home/curt/pybombs_180605/src/gnuradio/gr-blocks/lib/float_array_to_int.cc:33:14: error: ‘int64_t’ does not name a type
 static const int64_t MIN_INT =  INT32_MIN;
              ^
/home/curt/pybombs_180605/src/gnuradio/gr-blocks/lib/float_array_to_int.cc: In function ‘void float_array_to_int(const float*, int*, float, int)’:
/home/curt/pybombs_180605/src/gnuradio/gr-blocks/lib/float_array_to_int.cc:39:5: error: ‘int64_t’ was not declared in this scope
     int64_t r = llrintf(scale * in[i]);
     ^
/home/curt/pybombs_180605/src/gnuradio/gr-blocks/lib/float_array_to_int.cc:40:9: error: ‘r’ was not declared in this scope
     if (r < MIN_INT)
         ^
/home/curt/pybombs_180605/src/gnuradio/gr-blocks/lib/float_array_to_int.cc:40:13: error: ‘MIN_INT’ was not declared in this scope
     if (r < MIN_INT)
             ^
/home/curt/pybombs_180605/src/gnuradio/gr-blocks/lib/float_array_to_int.cc:42:18: error: ‘MAX_INT’ was not declared in this scope
     else if (r > MAX_INT)
                  ^
/home/curt/pybombs_180605/src/gnuradio/gr-blocks/lib/float_array_to_int.cc:44:31: error: ‘r’ was not declared in this scope
     out[i] = static_cast<int>(r);
                               ^
gr-blocks/lib/CMakeFiles/gnuradio-blocks.dir/build.make:4635: recipe for target 'gr-blocks/lib/CMakeFiles/gnuradio-blocks.dir/float_array_to_int.cc.o' failed
make[2]: *** [gr-blocks/lib/CMakeFiles/gnuradio-blocks.dir/float_array_to_int.cc.o] Error 1
CMakeFiles/Makefile2:2193: recipe for target 'gr-blocks/lib/CMakeFiles/gnuradio-blocks.dir/all' failed
make[1]: *** [gr-blocks/lib/CMakeFiles/gnuradio-blocks.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
PyBOMBS.monitor_process() - DEBUG - Thread signaled termination or returned
PyBOMBS.monitor_process() - DEBUG - Return value: 2
PyBOMBS.Packager.source - ERROR - Build failed. See output above for error messages.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package gnuradio:
PyBOMBS.Packager.source - ERROR - Build failed.
PyBOMBS.rebuild - ERROR - Error rebuilding package gnuradio. Aborting.
